name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'gw-athena-test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./src/
      
    - name: Build
      run: dotnet build ./src/Athena.sln --no-restore --configuration Release
      
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
      # comma separated list of XML/JSON/YAML files in which tokens are to be substituted. Files names must be specified relative to the folder-path.
        files: '${{env.DOTNET_ROOT}}/src/src/Web.App/appsettings.json'
      env:
        ApplicationInsights:InstrumentationKey: ${{ secrets.APPINSIGHTS_INSTRUMENTATION_KEY }}
      
    - name: Test
      run: dotnet test ./src/Athena.sln --no-build --verbosity normal
      
    - name: Publish
      run: dotnet publish ./src/Web.App/Web.App.csproj --no-build -c Release -o ${{env.DOTNET_ROOT}}/athena
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/athena      

  deploy:  
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps: 
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        # Artifact name
        name: .net-app
        
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: Azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B633D79EA1AB4C3CA72CC3D143159165 }}
        package: .
